--- 
- hosts: all
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      update_cache: yes
      state: present
  - name: install apache2
    apt:
      name: apache2
      state: present

  - name: start the service
    service:
       name: apache2
       state: restarted
